"""
This type stub file was generated by pyright.
"""

from datetime import datetime

class SchemaGETMixin:
    """
    Миксинка для всех GET схем (scheme)
    Поля соотвествуют полям из backend.src.database.core.base.Base
    """
    id: int
    created_at: datetime
    updated_at: datetime
    ...


