"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel
from ._get_mixin import SchemaGETMixin

class UsersPOSTSchema(BaseModel):
    username: str
    password: str
    ...


class UsersGETSchema(UsersPOSTSchema, SchemaGETMixin):
    is_superuser: bool
    ...


class UsersOnlyUsernameSchema(BaseModel):
    username: str
    ...


