"""
This type stub file was generated by pyright.
"""

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

async def make_async_session(session_maker: async_sessionmaker = ...) -> AsyncSession:
    ...

