"""
This type stub file was generated by pyright.
"""

from sqlalchemy.ext.asyncio import AsyncSession
from app.schemas.users import UsersGETSchema, UsersOnlyUsernameSchema, UsersPOSTSchema
from app.schemas.generic import BoolSchema

router = ...
@router.post('/create', summary="Новый пользователь")
async def user_register(data: UsersPOSTSchema, session: AsyncSession = ...) -> UsersGETSchema:
    ...

@router.post('/check_username', summary="Проверить уникальность имени пользователя")
async def check_username(data: UsersOnlyUsernameSchema, session: AsyncSession = ...) -> BoolSchema:
    ...

