"""
This type stub file was generated by pyright.
"""

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import Executable, Result
from typing import Any

class ServiceBase:
    def __init__(self, session: AsyncSession) -> None:
        ...
    
    @property
    def session(self): # -> AsyncSession:
        ...
    
    async def execute(self, statement: Executable) -> Result[Any]:
        ...
    


