"""
This type stub file was generated by pyright.
"""

from ..schemas.users import UsersGETSchema, UsersOnlyUsernameSchema, UsersPOSTSchema
from ._base import ServiceBase
from ..schemas.generic import BoolSchema

class UserService(ServiceBase):
    async def new(self, data: UsersPOSTSchema) -> UsersGETSchema:
        ...
    
    async def login(self, data: UsersPOSTSchema) -> UsersGETSchema:
        ...
    
    async def check_username_uniqueness(self, data: UsersOnlyUsernameSchema) -> BoolSchema:
        ...
    


