"""
This type stub file was generated by pyright.
"""

from sqlalchemy.orm import Mapped
from .. import ORMBase

class User(ORMBase):
    _post_schema = ...
    _get_schema = ...
    username: Mapped[str] = ...
    password: Mapped[str]
    is_superuser: Mapped[bool] = ...


