"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from pydantic_settings import BaseSettings

BASE_PATH = ...
ENV_FILE_PATH = ...
@lru_cache(maxsize=128)
def parse_url(url: str) -> str:
    ...

class EnvConfig(BaseSettings):
    model_config = ...
    DOMAIN: str
    BACKEND_PORT: int = ...
    SECRET_KEY: str
    FIRST_SUPERUSER: str
    FIRST_SUPERUSER_PASSWORD: str
    ENVIRONMENT: str
    STACK_NAME: str
    DATABASE_URL: str
    @lru_cache()
    def get_db_url(self): # -> str:
        ...
    


config = ...
