"""
This type stub file was generated by pyright.
"""

from sqlalchemy.ext.asyncio import AsyncEngine, async_sessionmaker
from functools import lru_cache

@lru_cache()
def get_default_db_engine() -> AsyncEngine:
    ...

@lru_cache()
def get_session_maker(_engine: AsyncEngine = ...) -> async_sessionmaker:
    ...

