"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Any
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncAttrs, AsyncSession
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr

class Base(AsyncAttrs, DeclarativeBase):
    __abstract__ = ...
    _post_schema: type(BaseModel)
    _get_schema: type(BaseModel)
    id: Mapped[int] = ...
    created_at: Mapped[datetime] = ...
    updated_at: Mapped[datetime] = ...
    @classmethod
    @declared_attr.directive
    def __tablename__(cls) -> str:
        ...
    
    @classmethod
    async def create(cls, session: AsyncSession, data: Any) -> Any:
        ...
    
    @classmethod
    async def get(cls, session: AsyncSession, pk: int) -> Any:
        ...
    


