"""
This type stub file was generated by pyright.
"""

from sqlalchemy.ext.asyncio import AsyncSession

class AtomicTransaction:
    def __init__(self, session: AsyncSession) -> None:
        ...
    
    async def __aenter__(self): # -> Self:
        ...
    
    async def __aexit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    


